### ISSUE TITLE
bower no found

### ISSUE THREAD

**Issue by Angularjschile** [nobitagit/ng-material-floating-button#1]
install from bower return package no found

**Comment by adriendomoison** [comment]
Hello, could you make it public now? I would like to use it in prod :)

**Comment by nobitagit** [comment]
It's public already, both via npm and bower so you choose your favorite method.

**Comment by adriendomoison** [comment]
uh uh, thank you for your answer but it doesn't work with me :
--
bower.json :
--
"dependencies": {
    "material-design-icons": "2.0.0",
    "ng-material-floating-button": "0.6.1"
  },
--
bower install
--
? May bower anonymously report usage statistics to improve the tool over time? Yes
bower ng-material-floating-button#0.6.1        ENOTFOUND Package ng-material-floating-button not found

Any idea?
