### ISSUE TITLE
adjust mfb-directive controller annotation for ng-strict-di

### ISSUE THREAD

**Issue by dohomi** [nobitagit/ng-material-floating-button#15]
Hi,
in ng-strict-di mode the controller of ```mfbMenu```and ```mfbButton```  is missing the ```$scope```service:
```

(...)
 controller: ['$scope', function($scope){
        return ctrl($scope, iconTemplate);
      }]
(...)
```
Would be great if you would add this. Cheers

**Comment by nobitagit** [comment]
that's right, will do before merging to master.
