### ISSUE TITLE
How to access menu state?

### ISSUE THREAD

**Issue by MichaelCPGordon** [nobitagit/ng-material-floating-button#16]
Hi there,

I can't seem to figure out how to access and modify a menu button's state from within a controller in an angular/ionic app.
I'm trying to change the opacity of the page whenever the button's menu is open.

Cheers

**Comment by nobitagit** [comment]
Hi there, I see what you mean. The button state as of now is meant to control the menu from outside but it's not updated by 2 way data binding. 
Anyway your use case seems legit, I'll have to make a quick fix for this.

**Comment by nobitagit** [comment]
Updated and should be fixed for now.
This is just a quick fix, code can be improved but should allow you to do what you need and the public API hasn't changed. 

There's a catch for now though.   
If you're using `click` toggling it will work out of the box and the menuState variable will be updated when clicking.

if you're using `hover` the 2 way update is disabled for now. It would actually work as expected for Angular (the relevant code is just commented out for now) but there's a CSS fix to do as setting the state to open automatically shows all labels without waiting for mouse to hover on them (which is not that bad but also not quite right). I will have to tweak the css of the original component for this to work as expected.

Anyway if you need to change some class when the menu is open with `hover` toggling you can refer to the demo (see line 30 of index.html). You can just listen to `mouseenter` and `mouseleave` events and manipulate your custom variable from there. 

I know it's not ideal to use another variable but shouldn't be that bad as a quick fix for now.
