### ISSUE TITLE
updated to 0.3.2 -> got 404 Not Found - http://ip-from-my-machine:9016/button.tpl.html

### ISSUE THREAD

**Issue by ibrainventures** [nobitagit/ng-material-floating-button#17]
and also for the menu.tpl.html

using angular 1.3.15

and i am using not the bootstrap css libs .. (may this helps) .. using my own css lib

**Comment by nobitagit** [comment]
are you running the demo using a server? As this is an external template you need to start a server at the root of your project.

**Comment by nobitagit** [comment]
@ibrainventures you were actually right, silly mistake on my part.
Updated to 3.3 should fix the issue, let me know if you encounter any other problem.
