### ISSUE TITLE
Firefox issue: 

### ISSUE THREAD

**Issue by robertbaker** [nobitagit/ng-material-floating-button#21]
![capture](https://cloud.githubusercontent.com/assets/907301/7170215/f7fe5bd6-e380-11e4-8d6d-be0222f368af.PNG)
![capture2](https://cloud.githubusercontent.com/assets/907301/7170231/16cfa2a4-e381-11e4-902f-2205a6dc870d.PNG)
The icons are off center in firefox.

**Comment by xeor** [comment]
I've seen this as well, kinda, in Chrome (and firefox).
The problem I had was when using the Angular Material template, and with only some icons (svg), and only on the main button, both in resting, and active -state.
The svg icon itself looked fine, and was filling the correct size. However, it ended up being off-center.

The svg I had problem with was the material design "plus":
```svg
<svg style="width:24px;height:24px" viewBox="0 0 24 24">
    <path fill="#000000" d="M19,13H13V19H11V13H5V11H11V5H13V11H19V13Z" />
</svg>
```

**Comment by xeor** [comment]
Try out angular material 0.9. It is currently in rc2, but fixed this issue for me.. `bower install angular-material#~0.9`

**Comment by robertbaker** [comment]
I use the latest master and update 3x a day as they make changes.

Still having the placement incorrect in firefox. Chrome it looks fine.

**Comment by xeor** [comment]
You are right.. It looks off in firefox in my test. I saw it fixed my initial issue in Chrome, so I thought it was ok. But not in Firefox..
