### ISSUE TITLE
Not work on ionic/phonegap hybird mobile app (ios/android)

### ISSUE THREAD

**Issue by gordonlukch** [nobitagit/ng-material-floating-button#22]
I tried it on ionic, it seem not work on ios and android, :~(

**Comment by nobitagit** [comment]
Never tried Ionic so I can't confirm or know what's not working there, sorry. If you have a public accessible demo let me know.

**Comment by GustavoCostaW** [comment]
For me works fine with cordova.

**Comment by gordonlukch** [comment]
I just simple add related css and js to header...  few lines code copy from
example:
...
    
    <link href="lib/angular-material/angular-material.css" rel="stylesheet">
    <script src="lib/angular-aria/angular-aria.min.js"></script>
    <script src="lib/angular-animate/angular-animate.js"></script>
    <script src="lib/angular-material/angular-material.min.js"></script>

    <link href="lib/ng-mfb/mfb/src/mfb.css" rel="stylesheet"/>
    <script src="lib/ng-mfb/src/mfb-directive.js"></script>

    
    <script src="cordova.js"></script>
....
....
        <nav mfb-menu position="br" effect="slidein-spring"
             active-icon="ion-close" resting-icon="ion-plus-round"
             toggling-method="click">
          <button mfb-button icon="ion-paintbrush" label="write
text"></button>
          <button mfb-button icon="ion-hammer" label="hammer"></button>
        </nav>
...
..

I work on local browser only(ionic serve --lab), but it don't work on
device or emulator...

Could you help? any hints? thank you.



Best Regards,
Gordon

**Comment by gordonlukch** [comment]
Just create an other testing ionic blank project and found, It is fine if install mfb only. But it don't work after install angular-material. It seem to be angular version conflict.  :~(

**Comment by GustavoCostaW** [comment]
works fine for me in angular v1.3.15

I use Angular Material too.

**Comment by gordonlukch** [comment]
Thanks, i will try cordova later.

**Comment by gordonlukch** [comment]
Great! test on cordova, without any problem. Just problem on ionic only. Thank you.

**Comment by paulogr** [comment]
It works on Ionic, I just tested !

You must put the mfb-menu outside ion-content.

Holpe it helps.

**Comment by gordonlukch** [comment]
Indeed, i had removed all ion related elements (included ion-content on the test page. I may test again, put all ion back and put mfb-menu outside ion as yours.

**Comment by gianvi** [comment]
Hi Guys, I'm looking for a solution for this problem: the menu doesn't work on mobile (browser or build app)...instead work good on web desktop browser.
I tried to move it out from the ionic-content but nothing is changed. @paulogr can u show your solution? 
thanks in advance

**Comment by gordonlukch** [comment]
my test still not work on ionic. Just cordova work fine.

**Comment by gianvi** [comment]
...with or without ion (html) elements? 
in my case (using the ionic web elements) building app for mobile with ionic or cordova doesn't change the result: the mfb-menu doesnt work, but I would like to understand if the problem is a conflict with the ionic system or with angular-material

**Comment by gordonlukch** [comment]
i use cordova to create a new project, use mfb + angular-material without problem.  Just problem when i  create project by ionic, with or without ion elements, it also not work.

**Comment by grrrian** [comment]
if you are using a gulpfile that loads all your scss, you can add ```@import "lib/ng-mfb/mfb/src/mfb.scss";``` to that file (e.g. app.scss)

**Comment by mohamedRhaiem** [comment]
don't set the mfb-menu div the ion-content ,place it to the ion-view it will work.
