### ISSUE TITLE
increase the animation speed

### ISSUE THREAD

**Issue by GustavoCostaW** [nobitagit/ng-material-floating-button#23]
I wanted to increase the animation speed is possible?

**Comment by nobitagit** [comment]
The animation can be controlled from scss by changing the appropriate variable, in your case [this one](https://github.com/nobitagit/ng-material-floating-button/blob/master/mfb/src/mfb.scss#L87).

To see how to override this variable from your own scss you might want to look at [these docs](https://github.com/nobitagit/ng-material-floating-button/tree/master/mfb#scsscss). Let me know if you have any doubts.

**Comment by GustavoCostaW** [comment]
Thx for help! @nobitagit
