### ISSUE TITLE
No touch support

### ISSUE THREAD

**Issue by vrracing** [nobitagit/ng-material-floating-button#3]
Currently depends on :hover and when tested with iPad2 on the demonstration page it does not work.

**Comment by nobitagit** [comment]
Yes, touch support is yet to come and in the to-do list as I am aware it's a major feature.

**Comment by nobitagit** [comment]
Just to update on this:

I added click and touch support to the original component (see [its repo here](https://github.com/nobitagit/material-floating-button)) today. On the next few days hopefully i will have time to get it ported to the angular version.
