### ISSUE TITLE
Q: When will package be available on NPM

### ISSUE THREAD

**Issue by lufecir** [nobitagit/ng-material-floating-button#31]
Hello, 

We would love to use ng-material-floating-button in our application. It's looking really nice.

But we are using only NPM for dependency management in our application, not Bower. I noticed everything is prepared for publishing the floating-button component on NPM, but I could not find it in the NPM registry.
Did I miss it?  Or do you have short term plans for publishing the component on NPM? If so, for when would this be scheduled? 

Kind regards,

Luc Feys

**Comment by nobitagit** [comment]
You are right, everything was set to do it (i even placed a checkbox in the todo to remind myself..) but i still did not publish it on npm... now it's done, I just needed a little nudge, clearly :smile:.

You can go ahead and test it with:

```
npm i ng-material-floating-button
```

I'll leave this open as i just publish it right now, so there might be something wrong. Feel free to report here any problems, or close it in case everything's ok.

**Comment by lufecir** [comment]
Sorry for not getting back to you earlier. I wanted to test first and then forget to provide you with an update.

It's working fine. Thanks a lot for the quick response.

**Comment by nobitagit** [comment]
:+1:
