### ISSUE TITLE
using angular-material resting icon position is at the top instead of center (firefox and chrome)

### ISSUE THREAD

**Issue by robertbaker** [nobitagit/ng-material-floating-button#33]
Using the latest angular-material 0.9.0-rc3.

I think the changes to md-fab icon line height in the past few days caused this (bad timing lol). Both Chrome and Firefox (didn't test the others).

![capture](https://cloud.githubusercontent.com/assets/907301/7395264/aaf96f06-ee4d-11e4-971b-d5d347b9b9e5.PNG)

**Comment by nobitagit** [comment]
If it's still a release candidate we can wait a bit I guess, but it's good to know. 
Let's leave this open and will surely tackle the problem as soon as 0.9 is officially landed, thanks for chiming in.

**Comment by robertbaker** [comment]
@nobitagit  0.9.0 is out.

**Comment by nobitagit** [comment]
Fixed in v0.5.0

**Comment by robertbaker** [comment]
Not so fast. Firefox is still not aligned.
