### ISSUE TITLE
Use the offical material-design-icons with $mdIconProvider?

### ISSUE THREAD

**Issue by cebor** [nobitagit/ng-material-floating-button#35]
Is it possible to use the material-design-icons via the [$mdIconProvider](https://material.angularjs.org/#/api/material.components.icon/service/$mdIconProvider) ?

I implemented like this, but it does not work.

```javascript
$mdIconProvider
      .icon('account-circle', 'bower_components/material-design-icons/action/svg/production/ic_account_circle_24px.svg')
      .icon('more-vert', 'bower_components/material-design-icons/navigation/svg/production/ic_more_vert_24px.svg');
```

```html
<nav mfb-menu position="br" effect="zoomin" label="hover here"
     active-icon="more-vert" resting-icon="more-vert"
     toggling-method="hover">
  <button mfb-button icon="account-circle" label="menu item"></button>
</nav>
```

**Comment by nobitagit** [comment]
Hi there,

made a quick demo myself to try out before answering and it seems to work for me.
I pushed this demo in its own repo, you can take a look [here](https://github.com/nobitagit/ngmat-test/blob/master/app/index.html#L69) and see if it does work for you too.

**Comment by cebor** [comment]
Ok i missed the `template-url` attribute, thx now its working :+1:

**Comment by cebor** [comment]
Maybe you can add this to the example in your [README.md](https://github.com/nobitagit/ng-material-floating-button#basic-setup)

**Comment by cebor** [comment]
Sorry but i have one more question: Is it possible to style the buttons with the [theming classes](https://material.angularjs.org/#/Theming/02_declarative_syntax) ?

**Comment by nobitagit** [comment]
Template urls are documented in the Readme already, see [here](https://github.com/nobitagit/ng-material-floating-button#element-attributes).

For you secondo question there's already an [issue here](https://github.com/nobitagit/ng-material-floating-button/issues/18), so not really possible out of the box atm. You may want to tackle this somehow by [creating your own template](https://github.com/nobitagit/ng-material-floating-button#customising-templates).
