### ISSUE TITLE
No way to close menu after click unless user moves mouse out of the way

### ISSUE THREAD

**Issue by onexdata** [nobitagit/ng-material-floating-button#4]
Because this is entirely CSS, it appears there is no way to close the menu when someone clicks an item, am I missing something?

I assigned an ng-click to the mfb-button item which I use to launch an action, but the user's mouse is still over the button, and it remains displayed open by CSS.

Is there a way to work around this?

**Comment by nobitagit** [comment]
I see what you mean, and yes, you are right, this is not possible at the moment.

I think that when touch support will be added (as pointed in issue #3 ) a class to open/close will be available also, so the tool won't rely solely on css. I guess that the best way there would be to remove the "open" class once a user clicks on a button.

Sorry I can't be more helpful right now, but hopefully in the next few days I'll have the time to look into it.

**Comment by nobitagit** [comment]
With the latest update it's now possible to open and close the menu programmatically. In your case the best way is probably to let the user open the menu with a click and programmatically close it after she/he clicks on a button.

**Comment by onexdata** [comment]
Awesome! Thank you very much! :)
