### ISSUE TITLE
mfb-directive.js causes error when using ng-strict-di

### ISSUE THREAD

**Issue by atorma** [nobitagit/ng-material-floating-button#41]
In version 0.6.0, there are two injections that cause an application to fail when using ng-strict-di.

One is on line 65
```javascript
mfb.directive('mfbButtonClose', function($log) {
    ...
});
```
Another is on line 95 (in mfbMenu directive)
```javascript
controller: function($scope, $attrs) {
   ...
}
```

**Comment by nobitagit** [comment]
Thanks for reporting.
Please check out v0.6.1 and let me know if you still have errors.

**Comment by atorma** [comment]
Works now - cheers!
