### ISSUE TITLE
Icons don't show up in Chrome

### ISSUE THREAD

**Issue by caribnow** [nobitagit/ng-material-floating-button#45]
The icons are not showing up in Chrome. I am using grunt to start app locally. When I switch to font awesome, which does show up, the icons are not centered.

**Comment by nobitagit** [comment]
icons are pulled in from a cdn in the demo, so you should import them on your index.html `<head>`. Never tried with Font awesome so there might be some css to be tweaked in that particular case.

**Comment by caribnow** [comment]
Got it. I will stick with your fonts. Works now.
