### ISSUE TITLE
Is there a way to position the button within an element instead of within the viewport?

### ISSUE THREAD

**Issue by B3nCr** [nobitagit/ng-material-floating-button#46]
I want the FAB to sit inside a certain element and form the menu for that element. I can't work out the CSS to change that so it stays within the parent element.

**Comment by nobitagit** [comment]
Never tried so no idea on this one. 
It *might* not be so trivial due to the fixed position of the component in the CSS.
Can you share some fiddle/plunkr of what you've tried or at least a demo of the starting conditions?

**Comment by dohomi** [comment]
@B3nCr this should work without big issues, just make sure that the parent container contains ```position:relative```stylesheet.
