### ISSUE TITLE
Cannot close menu programmatically

### ISSUE THREAD

**Issue by dziamid** [nobitagit/ng-material-floating-button#47]
I am binding menu-state to a property of my controller like in the docs:
```
    <nav mfb-menu position="tr" effect="zoomin" toggling-method="click"
         menu-state="vm.FabModel.state"
         active-icon="clear" resting-icon="add" template-url="account/fab/menu.html">
      <button mfb-button aria-label="Comment" icon="comment" label="Comment"
              template-url="account/fab/button.html" mfb-button-close></button>
    </nav>
```
When I open\close fab - the property get's updated, however when I update a property the fab does not close\open **until you hover a mouse over it**.

**Comment by nobitagit** [comment]
Hi if you're still having this issue would you mind sharing a plunkr or some live code I can look to?

**Comment by dziamid** [comment]
I am not using `toggling-method="click"` anymore, so the problem is not relevant.
