### ISSUE TITLE
Mutliple buttons

### ISSUE THREAD

**Issue by srednas** [nobitagit/ng-material-floating-button#50]
Is it possible to display multiple menu buttons on the same screen? E.g: Bottom left menu has certain buttons rating to requirement A, Bottom right menu has certain buttons relating to requirement B but neither menu must display it's buttons when the other is clicked.

**Comment by nobitagit** [comment]
It definitely was some time ago (see an [example on Codepen](http://codepen.io/nobitagit/pen/ZYWVKw) I made some time ago). 

The code has changed quite a lot, but it *should* still be possible, but only way is trying. Did you make some tests?
