### ISSUE TITLE
Floating button should use accent color

### ISSUE THREAD

**Issue by rubenlagus** [nobitagit/ng-material-floating-button#51]
According to [Material design](http://www.google.com/design/spec/style/color.html#color-ui-color-application):

> Use the accent color for your primary action button and components like switches or sliders

Current templates use `md-primary`, can you add an option to set the class for the buttons?

Thanks

**Comment by nobitagit** [comment]
I guess it's doable, care to make a PR for this? 
Otherwise as a quick solution you can probably use a custom template you pass to the directive containing the classes you need.

**Comment by rubenlagus** [comment]
Yep, I can make a PR with the change `md-primary`to `md-accent`, but I think that it should be a better option to add the possibility to set it in the own directive as another attribute.
