### ISSUE TITLE
How to associate callbacks to the buttons?

### ISSUE THREAD

**Issue by ivamluz** [nobitagit/ng-material-floating-button#6]
What's the best way to associate callbacks to be called when the buttons are clicked?

I've tried using ng-click, but it doesn't work as expected on mobile devices when main button is clicked. Instead of opening the menu, it fires the callback associated to the main button.

I've found a way to circumvent the issue. I'm going to fork the project and open a pull request, so you can evaluate it.

Thanks for making the component available.

[]s
Ivam

**Comment by nobitagit** [comment]
I created a bin for this here: http://jsbin.com/hawica

I can click  to open the menu and then get a different function call for each button without triggering the whole menu .
Seems to be working fine for me, or maybe I am misunderstanding your issue?

**Comment by ivamluz** [comment]
Thanks for getting back.

Actually, I was talking about associating an action to the main button. On Inbox, when you click the + button, it becomes a pencil. Clicking the pencil, triggers the main composition action.

It gets worse when you are accessing from a mobile device. If you associate an action to the main button and tap it, the action is simply triggered, and the menu doesn't get open, making it impossible to access the child actions.

I implemented this behavior here: https://github.com/ivamluz/ng-material-floating-button/commit/3df094bb918bcd1c54e901cf0ae38c8211c89ba7

If you are interested, please let me know and I'll be happy to create a pull request for this.

**Comment by nobitagit** [comment]
Oh, now I see what you mean and yes, you are totally right, the event bubbles up and triggers the main button.

As a quick solution the event propagation can be easily stopped by passing the event as an argument to the function and stop its propagation. Something like:

```html
<mfb-button ng-click="logThis( $event );">
```
And then stop the propagation is the function itself:

```js
logThis(evt){
        // do something....
    evt.stopPropagation();
};
```

Another bin for this here: http://jsbin.com/vugewu/

I didn't think of associating any callback to the main button apart from the default toggling one, but it's definitely a scenario worth considering.
I will reference this issue in docs for now then take a look at your solution and see how this is best implemented. Many thanks for pointing this out.

**Comment by ivamluz** [comment]
Nobita (is that right?),

I'm not sure stopPropagation() solves the issue.

As I see it, when you click the closed button, it should not call logThis(). Instead, it should open the menu. Then, when you click the main button again (with the menu open), it shoud call logThis().

Makes sense to you?

**Comment by ivamluz** [comment]
One additional note.

Implementing the main button behavior the way I suggested has a collateral effect. We aren't able to close the menu on mobile devices, unless a menu item is clicked.

I'm currently implementing a behavior to close the menu when the user clicks outside of it. Will let you know once it's done, so you can take a look.

**Comment by nobitagit** [comment]
Ok, if this time I get it right what you want is something very close to what happens in Google Inbox, where what here is called "main button" actually performs 2 actions:

1. it opens the menu when *hovered*
2. it opens a new message when *clicked*

If that is the case my doubt is more logical than technical. How to implement such a feature so that a user (assuming i understood properly and we are talking about the same behaviour) is able to close the menu then, due to the fact that what should be a "close button" is now performing a different action? 
I mean, in case of mouseEnter/mouseOut (see Inbox) it's quite clear, but when the behaviour is changed to click the solution is not as obvious.

Hopefully I got it right this time, if that's not the case then bear with me!

**Comment by nobitagit** [comment]
Ok, sorry, didn't read your second reply....

**Comment by ivamluz** [comment]
Does it make sense to you?

**Comment by ivamluz** [comment]
Off-click implemented here: https://github.com/ivamluz/ng-material-floating-button/commit/c7c2e396552980ef15bc64a9618d8b6e8a1acd59

**Comment by jgodi** [comment]
Any update on this? I was looking for something like this and was going to do a PR, but this seems to solve it.
