### ISSUE TITLE
How to close mfb using hardware back button on android?

### ISSUE THREAD

**Issue by chakhedik** [nobitagit/ng-material-floating-button#66]
Hi, I'm using mfb with ionic, I was able to close the mfb using soft back button by setting scope.var = 'closed' but the scope is not accessible through angular run(). How do I call to close mfb through angular run()?

**Comment by nobitagit** [comment]
I never had this requirement, so I am not 100% sure how to best get around this, but I think it's possible.

It's true indeed that you can't access `$scope` from run blocks but if I am not mistaken you can access `$rootScope`. Maybe you can take a look at some suggestions [here](http://stackoverflow.com/questions/27253332/set-common-scope-variables-in-run) and [here](http://stackoverflow.com/questions/17371687/getting-scope-object-in-angulars-run-method).

A possible workaround could be to emit an event from the rootscope, listen to it in your controller/directive and change the value accordingly.

**Comment by chakhedik** [comment]
I found a workaround by placing  `$ionicPlatform.registerBackButtonAction` in controller so that we can access the `$scope` inside the callback. However, setting `$scope.var = 'closed'` alone wont be enough for hardware back button, we have to set attribute `'data-mfb-state'` to `'closed'` also, only then the mfb will be closed (require jquery). Here's the code for both closing mfb with soft and hard back button:

View
```
    <nav id="floatingButtonID" mfb-menu position="br" effect="zoomin" label="Menu"
         active-icon="ion-minus-round" resting-icon="ion-plus-round"
         toggling-method="click" menu-state="floatingButton">
        <button ng-click="share(url)" mfb-button icon="ion-share" label="Share"></button>
    </nav>
```

Controller
```
            $scope.floatingButton = 'closed';

            var deregisterHardBack = $ionicPlatform.registerBackButtonAction(function () {
                if ($scope.floatingButton === 'open') {
                    $scope.floatingButton = 'closed';
                    angular.element('#floatingButtonID').attr('data-mfb-state', 'closed');
                } else {
                    $ionicHistory.goBack();
                }
            }, 101);

            var oldSoftBack = $rootScope.$ionicGoBack;
            $rootScope.$ionicGoBack = function () {
                if ($scope.floatingButton === 'open') {
                    $scope.floatingButton = 'closed';
                } else {
                    $ionicHistory.goBack();
                }
            };
            var deregisterSoftBack = function () {
                $rootScope.$ionicGoBack = oldSoftBack;
            };

            $scope.$on('$destroy', function () {
                deregisterSoftBack();
                deregisterHardBack();
            });

```
