### ISSUE TITLE
how many child buttons does the component have

### ISSUE THREAD

**Issue by apovn** [nobitagit/ng-material-floating-button#70]
I see that number of default child button is 4. Where can I config it ?
Thanks

**Comment by apovn** [comment]
I see in mfb.css, we can config it:
mfb-component__list li:nth-child(4), 
mfb-component__list li:nth-child(5), ...

or another way, use compile css to build new css file.

Thanks

**Comment by nobitagit** [comment]
Yes, best way is to compile it. See [here](https://github.com/nobitagit/ng-material-floating-button#mfb-button-element).
