### ISSUE TITLE
Close when clicking away

### ISSUE THREAD

**Issue by FilmCoder** [nobitagit/ng-material-floating-button#78]
Hi,

Is it possible to make it so that if you click to open it, then click somewhere else on the screen, the button collapses?  Right now it stays open, even if you click away.  Thanks!

**Comment by nobitagit** [comment]
I left this feature out on purpose as I did not want to touch the `window` object and just deal as much as I could only with the namespace that this component creates.

Anyway it should be quite easy to do with custom code or some external third party script (see [here](http://stackoverflow.com/questions/12931369/click-everywhere-but-here-event)). 
Once you listen to that event just close the menu programmatically, as shown in docs.

Cheers.
