### ISSUE TITLE
How to change menus opening direction.. ?

### ISSUE THREAD

**Issue by manushvenkatesh** [nobitagit/ng-material-floating-button#79]
For now, "mfb-menu position" attribute changes only the position of the floating button, with the menus opening along the directions "top to bottom" or "bottom to top"..
How to make these menu open along the directions "right to left" or "left to right".. ?

**Comment by nobitagit** [comment]
Hi,

This is not a functionality that is provided out the box, so you will have to edit the scss, add a custom class and make it work in that direction. 

You can use [this file](https://github.com/nobitagit/ng-material-floating-button/blob/master/mfb/src/_/_slidein.scss) as an example, and see how it is imported [here](https://github.com/nobitagit/ng-material-floating-button/blob/master/mfb/src/mfb.scss#L305-L327).
