### ISSUE TITLE
How can i apply the ripple effect to the button?

### ISSUE THREAD

**Issue by sajeetharan** [nobitagit/ng-material-floating-button#8]
Is there a way to apply the ripple effect as it happens in the material design?

**Comment by nobitagit** [comment]
Hi there, I knew that this request would be coming, but I am not 100% sure that providing it out of the box is the way to go. 

What if for example this component is placed on a page where other elements already have a ripple effect, implemented in a different way? 

Anyway as I said, I haven't made up my mind on this one really so I have been testing the button together with an Angular directive like [this one](https://github.com/nelsoncash/angular-ripple), and with a different, integrated approach similar to [this one](http://codepen.io/Craigtut/pen/dIfzv) but as it currently stands it requires a little bit of work to get the effect done.

I will leave this open for now and mark it as feature request, if you come up with something useful please do post your results. Cheers.

**Comment by nobitagit** [comment]
In v0.4 Angular Material button is integrated optionally and brings in the ripple effect functionality.
